CREATE DATABASE r5jca6;
USE r5jca6;

CREATE TABLE GYARTO (
	adoszam int NOT NULL PRIMARY KEY,
	nev VARCHAR(30),
	telephely VARCHAR(30)
);

CREATE TABLE TERMEK (
	tkod int NOT NULL PRIMARY KEY,
	nev VARCHAR(50),
	ear int NOT NULL,
	gyarto int,
	FOREIGN KEY (gyarto) REFERENCES GYARTO(adoszam)
);
